### ISSUE TITLE
inventory does not appear to be expanded

### ISSUE THREAD

**Issue by akineton1830** [nea89o/Firmament#26]
![Screenshot_1 (1)](https://github.com/nea89o/Firmament/assets/168852256/121c4e7e-0d0b-46fc-8dce-a3f5bf01aee5)
It shows like this.

**Comment by nea89o** [comment]
The storage overlay is its own gui, available at /firm storage, i think. Is that what you mean?

**Comment by akineton1830** [comment]
![lastcroppedss](https://github.com/nea89o/Firmament/assets/168852256/9374af73-c78a-48d1-a65f-31a5b2f46906)
Yes, it should normally look like this, right?

**Comment by nea89o** [comment]
Yep, looks about right. Also why are you on dulkirs island?

**Comment by akineton1830** [comment]
The picture does not belong to me... My inventory is not like this, it is like the picture I first shared. Can you please tell me how I should set this up?

**Comment by nea89o** [comment]
If you do `/firm storage` instead of just `/firm` it should show that GUI.

**Comment by akineton1830** [comment]
![Screenshot_3](https://github.com/nea89o/Firmament/assets/168852256/f180b8a3-3fff-466a-8bcd-f1ac0f8c30f6)
This time, when I type this command, my main inventory does not appear. Can't we see it directly without writing a command?

**Comment by akineton1830** [comment]
![Screenshot_2](https://github.com/nea89o/Firmament/assets/168852256/9b9336a1-9319-4000-9e2c-0c3d437d1eeb)
Doesn't it appear when we click on Storage?

**Comment by akineton1830** [comment]
I noticed that it appears when we click on any backpack after typing the /firm storage command, but isn't there an easier way? In a mod in Forge version 1.8.9, clicking on the storage area showed all main inventory and backpacks.

**Comment by nea89o** [comment]
Yes, this one is an overview, not a full overlay. I might do that at a later point in time, but not right now.

**Comment by akineton1830** [comment]
Okay thank you
