### ISSUE TITLE
armour skull models texture pack format

### ISSUE THREAD

**Issue by nshjck** [nea89o/Firmament#46]
Could you clarify how the armour skull models work, I've looked through the documentation and can't figure out how it works

**Comment by nea89o** [comment]
I dont understand. Could you clarify what you want to do, what you read, and what questions you have? This is a very open ended question that seems pretty impossible to answer.

**Comment by nshjck** [comment]
Sorry for being unclear, I meant specifically the head model. I read through the documentation in Texture Pack Format.md, specifically the armour skull models and head model section, but after making a resource pack with seemingly the correct json file the head model remains the same.

**Comment by nea89o** [comment]
the head model replaces the item model if it is equipped on your head. what does your texturepack look like?

**Comment by nea89o** [comment]
Hmm, okay. Sometimes checking the log output can be helpful
