### ISSUE TITLE
Hide REI partial data warning

### ISSUE THREAD

**Issue by ThatGravyBoat** [nea89o/Firmament#52]
Since Firmament clears out the vanilla items and recipes itd be nice if it hid the REI partial data warning from being displayed.

The warning is from the [ImportantWarningsWidget](https://github.com/shedaniel/RoughlyEnoughItems/blob/17.x-1.21.2/runtime/src/main/java/me/shedaniel/rei/impl/client/gui/hints/ImportantWarningsWidget.java) which is always displayed when joining Hypixel and seemingly no way to turn it off just only a way to temporary hide it for your session while on the server and shows back up after reconnecting.

![2024-12-03_22 57 32](https://github.com/user-attachments/assets/768c16f6-26ec-4b31-9a7c-0ba4df83c3ef)

**Comment by nea89o** [comment]
![image](https://github.com/user-attachments/assets/2ea65a8e-5546-4228-b078-c3ff6a108bc9)
Seems like this is a new warning (newer than the REI version i use). I guess i will need to do some mixins for this.
